version: "3.7"
secrets:
  db_password:
    external: true
  gcp_credentials:
    external: true

services:
  pg_master:
    image: mesoform/postgres-ha:13-latest
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=testuser
      - PG_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_DB=testdb
      - STORAGE_BUCKET=gs://postgresql13/wal-g
      - GCP_CREDENTIALS=/run/secrets/gcp_credentials
    ports:
      - "5432:5432"
    secrets:
      - source: db_password
        uid: "70"
        gid: "70"
        mode: 0550
      - source: gcp_credentials
        uid: "70"
        gid: "70"
        mode: 0550
    networks:
      database:
        aliases:
          - pg_cluster
    deploy:
      placement:
        constraints:
        - node.labels.type == primary

networks:
  database: {}

volumes:
  pg_data: {}
